services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ~/data/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - ${MINIO_PORTS}
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ~/data/redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server
    ports:
      - ${REDIS_PORTS}